### ISSUE TITLE
No Schedules on Trains

### ISSUE THREAD

**Issue by bcwhite-code** [nyurik/fatul#5]
One of my SpaceEx blueprints (Space Launch System aka Space Elevator) has standard trains with pre-defined schedules.  Though the .json files would indicate that those schedules have been captured correctly, the exported blueprint does not seem to have them.

To reproduce:
- get the latest source here: https://github.com/bcwhite-code/brians-blueprints
- use fatul to export it: `fatul encode -v self-building-spacex $HOME/self-building-spacex-0.6.15.txt`
- import that into Factorio
- use /editor to place the Space Launch System (under the Rockets sub-book)
- look at the trains; they should have schedules but do not
- compare to latest (0.6.15) blueprint here: https://github.com/bcwhite-code/brians-blueprints/releases/tag/self-building-spacex (a direct export from Factorio)

Though this is SE, you should be able to do everything with Vanilla since it's not dependent upon anything SE.

Of note, some of the scheduled stops have non-ascii names.

**Comment by nyurik** [comment]
@bcwhite-code thx, could you create some simple reproducable export strings?  E.g. create a small train with a schedule, export it, save a file (raw), pass it through fatul by decoding and later encoding it, and see what the difference is?  I have reinstalled all my machines, and will need to reinstall factorio, but it can't happen until the next weekend (i'm away from my main machine).  This way i can debug it purelly on the text level, without importing/exporting to factorio. Thx!

**Comment by bcwhite-code** [comment]
Here's a small train with a schedule, as exported by Factorio:
```
0eNq9lc1u2zAMx18l0NlubCe2EwPdbTvt1AzYoQgCRWYcobJkSHK6IPB192FvuCcZFeejW7UM7qEnQxL5IymKfx/IWrTQaC4tKQ6EMyUNKR4PxPBKUuH27L4BUhBuoSYBkbR2K6GYqpXlOyBdQLgs4Rsp4m4ZEJCWWw495bjYr2Rbr0GjwcXfWE15tbUhfgRiG2XQS0kXEEmTeRqQPX6jvOuCV5zkwmFUVyp8phW6/psSx3fzbJanmKrSHGG0t4ruUpf8DneURkPZCuEJNxme9tyX9nQwJ459nHQ4Z+LjZMM5qY+T+57FDcjsVjfwmRnnoRV7AhtuWhDuZXnCzoan731N8+Ecb3vjaDAo8RYWD5+TBBuMw2fYFspWnKbv2g23zl+c9yN+vnjyUcCO4giMHyD85C48IM+U2xWqQXkM1/OQ1lANq5MiKI12Z3WQlGEgrMLtcfaEHlnULV111ziPvK7u+2LHBkLTUAYhnIIvR6NzHqNf33+QP10XW97sqS7HX6mxEC7aphH74XlucMKP5L9sqCyvRoxr1nKLGxewu+8N18auXgnjjmvbUnHVxt4i1FA6bXSKaqmT1yg4RXUlot096TyZ/O9WJ1kUvU8BlQaQt0v4gCW8vcc/b/f4ARj0SjKwyVA3eGOY2NLNxPHHVbz4zwVE0LVTFfJZGTtauJnAw9EXMO5wB9oc80lm8TSfJ3mWZOk0xwH7DRPzbIU=
```

After `fatul decode -v lost-schedule-before.json`, I get:
```
{
  "blueprint": {
    "item": "blueprint",
    "label": "Lost Schedlue Test",
    "shift_x": 395,
    "shift_y": 307,
    "version": 281479276265473,
    "entities": [
      {"name": "cargo-wagon", "inventory": null, "orientation": 0.5, "position": {"x": 0, "y": 4.96875}},
      {
        "name": "locomotive",
        "orientation": 0.5,
        "items": {"rocket-fuel": 1},
        "position": {"x": 0, "y": 11.96875}
      },
      {"name": "straight-rail", "position": {"x": 0, "y": 0}},
      {"name": "straight-rail", "position": {"x": 0, "y": 2}},
      {"name": "straight-rail", "position": {"x": 0, "y": 4}},
      {"name": "straight-rail", "position": {"x": 0, "y": 6}},
      {"name": "straight-rail", "position": {"x": 0, "y": 8}},
      {"name": "straight-rail", "position": {"x": 0, "y": 10}},
      {"name": "straight-rail", "position": {"x": 0, "y": 12}},
      {"name": "straight-rail", "position": {"x": 0, "y": 14}},
      {"name": "straight-rail", "position": {"x": 0, "y": 16}}
    ],
    "icons": [{"index": 1, "signal": {"name": "locomotive", "type": "item"}}],
    "schedules": [
      {
        "locomotives": [7],
        "schedule": [
          {
            "station": "Elevator/Re-Fuel",
            "wait_conditions": [{"compare_type": "or", "ticks": 60, "type": "inactivity"}]
          },
          {"station": "[img=entity/se-space-elevator]  Elevator ↑"},
          {
            "station": "Shipyard/Waste-Supply",
            "wait_conditions": [
              {"compare_type": "or", "type": "full"},
              {
                "compare_type": "and",
                "type": "circuit",
                "condition": {"comparator": "=", "constant": 0, "first_signal": {"name": "signal-red", "type": "virtual"}}
              },
              {"compare_type": "or", "ticks": 3600, "type": "inactivity"},
              {
                "compare_type": "and",
                "type": "circuit",
                "condition": {"comparator": ">", "constant": 0, "first_signal": {"name": "signal-green", "type": "virtual"}}
              }
            ]
          },
          {"station": "[img=entity/se-space-elevator]  Elevator ↓"},
          {"station": "Shipyard/Waste-Receive", "wait_conditions": [{"compare_type": "or", "type": "empty"}]}
        ]
      }
    ]
  }
}
```
which looks correct.  When I `fatul encode -v lost-schedule-before.json`, I get

```
0eNqtlMFu4jAQhl8F+ZwUQiCBSO1t97SnstIeKoSMGYJVx45shxahXPe+2jfcJ9lxTIFu3UpZVRyCZ8bfPzP2+EjWooFac2lJcSTcQkWKK1tEBF2DQNs3ZexgwXawQefgOxjn3IM2XElSjGfJJJ+P82ycTSd5GhGQllsOhhQPR784rGRTrUGTIomIpBUglFFdqviJlsiICJd7jFT6QArZCBERpTkaqO0kRjfTiNTKcL88kmdSpHO0YXiaJDfzbJZP2zZ6Izc+ywnFVKUs3wMJwV31xpG1Yo9g423jKk/aD2Rn78umZ1ljNeXlzsb4EeR92igPcSb9OfMQZ9qbkyQhTtafk4Y4eX9OsM+z/pxgn+f9OcE+J6PeoHGw0UnSH4SdXuJFZkr6yeNyA8/dxBleSirchtAw2EPtbN38dwjjJr0RpwG+xLp1fuXv3OZljMgXAXuKIzy8h/irG5+IPFFuV5jQpsvY85BWUw2rk6zSLgXOHtGbjS7ZSMpQE3tC2qVr0EXngVflre/X0EBsasoghpP4cjB4yWPw5+cv8nrrYsfrA9Wb4Q9qLMSLpq7FoU+e/v8WX6iO/E8MlZtLEOOaNdy9lGewOwG/xeWHMbfeiwm6Nxir33Jt7OrNeXlDrOGKv+faNhjVtoFMrruaZqNwXz+hgLt+BZQaQAZL+P8z/v3xGd8DA3/Pex4yVLW/fO7X/gUQ32yF
```

If I then `fatul decode -v lost-schedule-after.json`, I get the exact same json (i.e. no diff between before and after).  However, if I import the encoded intermediate into Factorio, the schedule is empty.

The actual schedule is attached:
![Screenshot (56)](https://user-images.githubusercontent.com/9848428/198167129-326e1381-8e06-4365-99a8-052cc992e112.jpg)

**Comment by nyurik** [comment]
Thanks @bcwhite-code , could you double check that if you import the original string, it does preserve the schedule?

**Comment by bcwhite-code** [comment]
I did and importing the original export worked fine.

**Comment by nyurik** [comment]
I think I know what the issue is.  The `"schedules": [...]` block has this entry `"locomotives": [7]` -- and 7 is the `entity_number`. Since they are all renumbered, 7 is no longer valid. Seems like an easy fix - I do the same renumbering for some other things too. Thanks for spotting it!

**Comment by nyurik** [comment]
Please test and let me know if it works. It is now part of the main branch. I have also applied it to the `sort-neighbours` branch - let me know which one you are using BTW.

**Comment by bcwhite-code** [comment]
Train schedules now show up in the exported blueprints so I'd say this is good.  Both of these changes can be merged into the main branch.

**Comment by nyurik** [comment]
done
