### ISSUE TITLE
Factorio 2.0

### ISSUE THREAD

**Issue by bcwhite-code** [nyurik/fatul#8]
I'm updating by "Brian's Trains" blueprints for Factorio 2.0.

I found that when I used Fatul to convert the exported blueprint into files and then converted those back to a single file, the import was missing power lines between the power poles.

Will you be updating your tool?

**Comment by nyurik** [comment]
hi, i will be happy to, but i don't have factorio 2 - i would need to see how json differs, and how we can preserve it. Perhaps we should set up more tests to ensure the right stuff is preserved?

**Comment by nyurik** [comment]
P.S. I updated mine to v2 - could you give smallest possible example of a failure so I could debug and add it as a test case?

**Comment by nyurik** [comment]
@bcwhite-code I think I found the problem - there is now a new entry called "wires" - similar to how locomotives' schedules are stored. I fixed it in https://github.com/nyurik/fatul/commit/739e38bab58f6d4c60d0937d88734a8fa4587237

**Comment by bcwhite-code** [comment]
Ah, I was just coming to post a test-case.  Let me try it out...
